spring.application.name=hospital

# MySQL - UPDATE THESE
spring.datasource.url=jdbc:mysql://localhost:3306/hospital_db
spring.datasource.username=root
spring.datasource.password=vijaykrishna@561
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret=HospitalAppSecretKey2024SaiVijayaKrishna
jwt.expiration=86400000

# Email - UPDATE THESE
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=saivijayakrishna.s@gmail.com
spring.mail.password=uaxi ehip rrtg bltb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port=8081
